# Generated by Django 5.1.7 on 2025-03-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号/工号')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('school', models.CharField(max_length=100, verbose_name='学校')),
                ('role', models.CharField(choices=[('STUDENT', '学生'), ('TERCHER', '教师'), ('ADMIN', '管理员')], default='STUDENT', max_length=10, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否是管理员')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
