# Generated by Django 5.1.7 on 2025-03-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', '学生'), ('TEACHER', '教师'), ('ADMIN', '管理员')], default='STUDENT', max_length=10, verbose_name='角色'),
        ),
    ]
