# Generated by Django 5.1.7 on 2025-04-17 05:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_group_size',
            field=models.IntegerField(default=3, verbose_name='最大小组人数'),
        ),
        migrations.AddField(
            model_name='course',
            name='min_group_size',
            field=models.IntegerField(default=1, verbose_name='最小小组人数'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='小组名称')),
                ('max_students', models.IntegerField(verbose_name='最大学生数')),
                ('min_students', models.IntegerField(verbose_name='最小学生数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_groups', to='course.course', verbose_name='课程')),
                ('students', models.ManyToManyField(blank=True, related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '小组',
                'verbose_name_plural': '小组',
                'ordering': ['-created_at'],
            },
        ),
    ]
