# Generated by Django 5.1.7 on 2025-04-17 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_max_group_size_course_min_group_size_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_group_size',
            field=models.PositiveIntegerField(default=3, verbose_name='最大小组人数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='min_group_size',
            field=models.PositiveIntegerField(default=1, verbose_name='最小小组人数'),
        ),
        migrations.AlterField(
            model_name='group',
            name='max_students',
            field=models.PositiveIntegerField(verbose_name='最大学生数'),
        ),
        migrations.AlterField(
            model_name='group',
            name='min_students',
            field=models.PositiveIntegerField(verbose_name='最小学生数'),
        ),
    ]
