# Generated by Django 5.1.7 on 2025-04-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_group_creator_alter_course_max_group_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='max_students',
            field=models.PositiveIntegerField(null=True, verbose_name='最大学生数'),
        ),
        migrations.AlterField(
            model_name='group',
            name='min_students',
            field=models.PositiveIntegerField(null=True, verbose_name='最小学生数'),
        ),
    ]
