# Generated by Django 5.1.7 on 2025-04-23 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_group_max_students_alter_group_min_students'),
        ('subject', '0007_alter_publicsubject_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('PRIVATE', '私有课题'), ('PUBLIC', '公开课题')], max_length=10, verbose_name='课题类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_subjects', to='course.course', verbose_name='课程')),
                ('private_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_subjects', to='subject.subject', verbose_name='私有课题')),
                ('public_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_subjects', to='subject.publicsubject', verbose_name='公开课题')),
            ],
            options={
                'verbose_name': '课程课题',
                'verbose_name_plural': '课程课题',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'private_subject'), ('course', 'public_subject')},
            },
        ),
    ]
