# Generated by Django 5.1.7 on 2025-04-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursesubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_subject_selections',
            field=models.PositiveIntegerField(default=3, verbose_name='最大课题选择数'),
        ),
    ]
