# Generated by Django 5.1.7 on 2025-04-24 04:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_max_subject_selections'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subjects', to='course.coursesubject', verbose_name='课程课题')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subjects', to='course.group', verbose_name='小组')),
            ],
            options={
                'verbose_name': '小组选题',
                'verbose_name_plural': '小组选题',
                'ordering': ['-created_at'],
                'unique_together': {('group', 'course_subject')},
            },
        ),
    ]
