# Generated by Django 5.1.7 on 2025-05-01 05:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_groupsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCodeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('description', models.TextField(blank=True, verbose_name='版本描述')),
                ('zip_file', models.FileField(upload_to='group_codes/zip/%Y/%m/%d/', verbose_name='ZIP文件')),
                ('total_files', models.IntegerField(default=0, verbose_name='文件总数')),
                ('total_size', models.BigIntegerField(default=0, verbose_name='总大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_versions', to='course.group', verbose_name='小组')),
            ],
            options={
                'verbose_name': '代码版本',
                'verbose_name_plural': '代码版本',
                'ordering': ['-created_at'],
                'unique_together': {('group', 'version')},
            },
        ),
        migrations.CreateModel(
            name='GroupCodeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文件内容')),
                ('size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('is_previewable', models.BooleanField(default=False, verbose_name='是否可预览')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='course.groupcodeversion', verbose_name='版本')),
            ],
            options={
                'verbose_name': '代码文件',
                'verbose_name_plural': '代码文件',
                'ordering': ['path'],
                'unique_together': {('version', 'path')},
            },
        ),
    ]
