# Generated by Django 5.1.7 on 2025-05-03 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_groupcodeversion_groupcodefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_submitted', models.BooleanField(default=False, verbose_name='是否已提交')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='course.groupcodeversion', verbose_name='代码版本')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='course.group', verbose_name='小组')),
            ],
            options={
                'verbose_name': '小组提交',
                'verbose_name_plural': '小组提交',
                'ordering': ['-created_at'],
                'unique_together': {('group', 'code_version')},
            },
        ),
    ]
