# Generated by Django 5.1.7 on 2025-05-03 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_groupsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubmissionContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='贡献度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_contributions', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='course.groupsubmission', verbose_name='提交')),
            ],
            options={
                'verbose_name': '提交贡献度',
                'verbose_name_plural': '提交贡献度',
                'ordering': ['-created_at'],
                'unique_together': {('submission', 'student')},
            },
        ),
    ]
