# Generated by Django 5.1.7 on 2025-04-09 05:41

import subject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_subject_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='subject_files/', validators=[subject.validators.validate_pdf_file, subject.validators.validate_file_size], verbose_name='课题原始描述文件'),
        ),
    ]
