# Generated by Django 5.1.7 on 2025-04-21 08:49

import django.contrib.postgres.fields
import subject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_subject_is_public_subject_public_review_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicsubject',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='max_students',
        ),
        migrations.AddField(
            model_name='publicsubject',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('C', 'C'), ('CPP', 'C++'), ('JAVA', 'Java'), ('PYTHON', 'Python')], max_length=10), default=['P', 'Y', 'T', 'H', 'O', 'N'], help_text='可多选', size=None, verbose_name='适用语言'),
        ),
        migrations.AddField(
            model_name='subject',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('C', 'C'), ('CPP', 'C++'), ('JAVA', 'Java'), ('PYTHON', 'Python')], max_length=10), default=['P', 'Y', 'T', 'H', 'O', 'N'], help_text='可多选', size=None, verbose_name='适用语言'),
        ),
        migrations.AlterField(
            model_name='publicsubject',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='public_subject_files/', validators=[subject.validators.validate_pdf_file, subject.validators.validate_file_size], verbose_name='课题原始描述文件'),
        ),
    ]
