# Generated by Django 5.1.7 on 2025-04-21 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_remove_publicsubject_max_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicsubject',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('C', 'C'), ('CPP', 'C++'), ('JAVA', 'Java'), ('PYTHON', 'Python')], max_length=10), default=list, help_text='可多选', size=None, verbose_name='适用语言'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('C', 'C'), ('CPP', 'C++'), ('JAVA', 'Java'), ('PYTHON', 'Python')], max_length=10), default=list, help_text='可多选', size=None, verbose_name='适用语言'),
        ),
    ]
